#!/bin/bash


# Install pathogen
# This is just to help managing plugins
mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

if [[ "$1" = "update" ]]
then
    for i in ~/.vim/bundle/*
    do
        echo "Updating $i"
        cd $i
        git pull
        cd -
    done
    exit 0
fi

# Link vimrc to .vimrc
ln -s $PWD/vimrc $HOME/.vimrc

# 
# All plugins
#

cd ~/.vim/bundle
# Kalisi color scheme
git clone https://github.com/freeo/vim-kalisi
# Fastfold
git clone https://github.com/Konfekt/FastFold.git
# Nerdtree  (and git support)
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/jistr/vim-nerdtree-tabs.git

# Syntastic (it requires syntax checkers, duh!)
git clone  https://github.com/scrooloose/syntastic.git
# Tabular (text aligner)
git clone git://github.com/godlygeek/tabular.git
# Rainbow Parentheses
git clone https://github.com/kien/rainbow_parentheses.vim
# Snippets
git clone https://github.com/tomtom/tlib_vim.git
git clone https://github.com/MarcWeber/vim-addon-mw-utils.git
git clone https://github.com/garbas/vim-snipmate.git
git clone https://github.com/honza/vim-snippets.git
# Vimtex
git clone https://github.com/lervag/vimtex.git
if [[ ! $(command -v zathura) ]]
then
    echo "Zathura is needed to use the synctex capabilities of vimtex"
fi

# FuGITive
git clone git://github.com/tpope/vim-fugitive.git
vim -u NONE -c "helptags vim-fugitive/doc" -c q

# Machit
git clone https://github.com/codescv/vim-matchit

# Pydoc
git clone https://github.com/fs111/pydoc.vim.git
