#!/bin/bash

install_package() {
    echo "Installing $1"
    if pacman -Q $1 &> /dev/null
    then
        echo "$1 already installed"
    else
        yay -S $1 
    fi
}


# Install language servers for coc.nvim
for i in ccls
do
    install_package $i
done

# Initialize all submodules
git submodule update --init --recursive
git pull --recurse-submodules

# Install the dependencies of coc
cd pack/plugins/start/coc.nvim/
npm install
cd -

# Install all coc extensions: https://github.com/neoclide/coc.nvim 
# Todo: try esbonio
echo "Installing vim coc extensions..."
vim -c ":CocInstall coc-pyright coc-vimtex coc-json coc-yaml coc-highlight coc-html coc-tsserver coc-cmake coc-css coc-git coc-nginx coc-rls coc-rome coc-sh"
